# Generated by Django 5.0.1 on 2024-02-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=225)),
                ('image', models.ImageField(upload_to='images/category')),
            ],
            options={
                'verbose_name': 'ژانر',
                'verbose_name_plural': 'ژانر ها',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=225)),
                ('image', models.ImageField(upload_to='images/game')),
                ('story', models.TextField()),
                ('game_play', models.CharField(blank=True, max_length=48, null=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('category', models.ManyToManyField(to='games.category')),
            ],
            options={
                'verbose_name': 'بازی',
                'verbose_name_plural': 'بازی ها',
            },
        ),
    ]
